### ISSUE TITLE
UX issue: Jarring Interface movements in install

### ISSUE THREAD

**Issue by co60ca** [paragonie/airship#105]
- [ ] Check this box if this is a security vulnerability.

### Summary
When installing the password is checked for password strength and the options for defaults and advanced configuration jump down the page once the message for password strength is displayed due to this file:
https://github.com/paragonie/airship/blob/89b4671962b3b8eb7b7fd0888a7a53b3ece8ba81/src/Installer/skins/js/admin_account.js.twig

Instead we should reserve space for password strength message but change the message depending on the given strength.

This is as major UX issue since when you release focus from the password box the options move down the page and it is for the option for default config to replace the physical location of the advance config option.

**Comment by paragonie-scott** [comment]
```css
#password_feedback {
    min-height: 2rem;
}
```
...would that do the trick?

**Comment by co60ca** [comment]
Still moves tbh, especially in different resolutions

**Comment by paragonie-scott** [comment]
Sigh. 5rem it is.
