### ISSUE TITLE
Settings page requires reload to show changes

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#110]
When changing settings on `/bridge/admin/settings`, the previous state is shown after saving instead of the new state. A reload shows then the new settings.

Instead, after saving the settings, there should be the new settings displayed.

**Comment by paragonie-scott** [comment]
This should've been fixed when I closed #73. Does this help? https://github.com/paragonie/airship/commit/102494129557a444e2fa8a29604bdc6d2518b0c8

**Comment by kelunik** [comment]
It's even worse. It throws an exception currently.

```
DEBUG ERROR: UnexpectedValueException

RecursiveDirectoryIterator::__construct(/var/www/airship/src/tmp/cache/csp_static): failed to open dir: No such file or directory

0

#0 /var/www/airship/src/Airship.php(508): RecursiveDirectoryIterator->__construct('/var/www/airshi...')
#1 /var/www/airship/src/Airship.php(190): Airship\list_all_files('/var/www/airshi...')
#2 /var/www/airship/src/Cabin/Bridge/Landing/Admin.php(218): Airship\clear_cache()
#3 /var/www/airship/src/Engine/AutoPilot.php(429): Airship\Cabin\Bridge\Landing\Admin->manageSettings()
#4 /var/www/airship/src/Engine/AutoPilot.php(264): Airship\Engine\AutoPilot->serve(Array, Array)
#5 /var/www/airship/src/public/index.php(153): Airship\Engine\AutoPilot->route()
#6 {main}<!-- Load time: 0.47474 s -->
```

**Comment by paragonie-scott** [comment]
What? Why is *that* throwing an exception?

**Comment by paragonie-scott** [comment]
The exception should be fixed in version 1.2.5, which if you wait an hour (or run `src/CommandLine/continuum.sh` manually), you should be updated. (If not, let me know there's a problem.)

**Comment by kelunik** [comment]
The exception is still there in `1.2.7`.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/7b90335f940244859512b47381cfda3612353d8e If this doesn't fix it, I have no idea what's wrong.

**Comment by paragonie-scott** [comment]
@kelunik Is this still happening in dev-master?

**Comment by kelunik** [comment]
After saving I get a page without the stylesheet, but no exception anymore.

**Comment by paragonie-scott** [comment]
The bad news: That's a bug.

The good news: It's a wholly unrelated bug. :)

I'm satisfied enough with that response to close this for now. I'll fix the other one soon.
