### ISSUE TITLE
Auto update doesn't work

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#111]
Keyggdrasil fails and doesn't install updates. There's no specific reason in the logs.

**Steps to Reproduce**

 - `git clone git@github.com:paragonie/airship`
 - `cd airship`
 - `git checkout v1.1.4`
 - `docker build -t airship:latest .`
 - `docker run --rm -ti --name airship -p 8001:80 airship:latest`
 - Setup Airship, setup to install minor updates, not only bugfixes
 - Make requests to trigger auto updater and wait for it to finish once it started

`root@4be3c9f968a6:/var/www/airship/src/tmp/logs# tail -f 2016-07-08.log`

`2016-07-08T12:37:01	info	"Automatic update started"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}`
`2016-07-08T12:37:03	alert	"Keyggdrasil failed for Airship core update"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}`
`2016-07-08T12:37:06	alert	"Keyggdrasil failed for Airship core update"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}`
`2016-07-08T12:37:06	info	"Automatic update concluded"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}`

**Comment by paragonie-scott** [comment]
I may have forgotten to configure a default notary during quick install. Can you try this?

1. Go to `{$bridge}/admin/notaries`
2. Add https://bridge.cspr.ng/notary (public key should be `ASm-gR36RK0vi9vO-FR2bevj220lG3TYPgKCze6NUWA=`)
3. Run `src/CommandLine/continuum.sh` manually

**Comment by paragonie-scott** [comment]
Actually, there was an upstream problem with CSPR.NG as well, where I accidentally had it set to rely on itself for verification, which obviously won't succeed. It should be fixed now.

**Comment by kelunik** [comment]
@paragonie-scott `cspr.ng` is already there by default:

![image](https://cloud.githubusercontent.com/assets/2743004/16693973/14b024a2-4538-11e6-91b3-93c63ab50163.png)

**Comment by paragonie-scott** [comment]
Did fixing the upstream issue (not a code change) fix this?

```sql

airship_test=# SELECT treeupdateid, merkleroot FROM airship_tree_updates ORDER BY treeupdateid DESC;
 treeupdateid |                                                            merkleroot
--------------+----------------------------------------------------------------------------------------------------------------------------------
           10 | 3c5277c172ba927f1e9ec3cf49bbc12be8822e1716f50d395b9a66299535007f26bf266aaeac08005ae358276f1e8632253b3015e107d325be921483afb314ee
            9 | cacf472a8ee5093a27ebbfc411c1f143b34784fcdd01458ee3a2ff9c3bce253e70e65a027d2a39317fd0a27372535a6d7db22a8623fd314ae3ee8851a2e48153
            8 | 7a96ba75565439571fb1d0c7df093d63e795d9fe30d5c1d75a5ce0a699a2a2f632be61410c92104da44bdbfe769e17eaa0281624e5487d2fd3617911f5ce8811
            7 | 85e2e463d5f3448c5a6dd37287a0dbf022dd8f7349c20aa692c5189779770e936b7b8d96b64b37fe4af78dd47ab226674e934be65e4b32a9e1e22d2d29a55d3b
            6 | 0e3b729c7d801e6d7e3bdd0e97fe81c1ea6aa92320558f980dc5c41d56fab2246238e51f44a5831d62ff9bfbb70ba7d99a82a0010d7501c2f7891f3aa547276e
            5 | 58c198c8b1816a42300b53a54c3077ae95c1a785db99eb04ac31cee4968210d1e4505b1d020ea85458bcdf2ba39c8210a58f5c9686405e1eabb0c6daebea4530
            4 | fea3fb23736d6393c822cb7cca9a36256c6c294f490d75ab43a4c884e65b853c45877e9f508c42eea158ac98db0aab8abb12742e31f6dbdfd5833db78d748679
            3 | 4ba3068a9ecb14a1b7f8d86740b8fd1da9e4bc0519d5c84eca1fffdcb49c580c34c5dedd333c0148b3f95aa994d0334f33308643bf235d825f4c6d8bf379b642
            2 | 940c0456c19d3606b27c89d15a82523f8fdb83928b4d27e027058a279665b124afc7af4188098704058bf067f0349b32c9a8c7f244499623d5d9f7b6e1fa986d
            1 | 99b4556c9506fd1742ca837e534553c9dcff5cdfae3ef57c74eb6175c6c8ffb9da04102a6a83c5139efd83c5e6f52cabc557ed0726652e041e214b8a677247ea
```

**Comment by kelunik** [comment]
Same thing there:

```
2016-07-09T10:08:20	info	"Keyggdrasil started"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}
2016-07-09T10:08:29	info	"Keyggdrasil concluded"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}
2016-07-09T10:08:29	info	"Automatic update started"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}
2016-07-09T10:08:30	alert	"Keyggdrasil failed for Airship core update"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}
2016-07-09T10:08:32	alert	"Keyggdrasil failed for Airship core update"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}
2016-07-09T10:08:32	info	"Automatic update concluded"	{"ip":"localhost","hostname":"localhost","port":null,"user_agent":"cli","referrer":null,"uri":"\/var\/www\/airship\/src\/CommandLine\/continuum.php"}
```

Just verify it yourself, I included all the required Docker commands to build the image. ;-)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/567cd169598726ff06b800b340e97f016a5b9c62 will fix it. 1.2.1 incoming in a moment.
