### ISSUE TITLE
New Motif for Version 2

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship#122]
Placeholder ticket.

We're going to hire someone with web design skills in the near future to design a better default motif. Airship classic will still be an option, but the newer one (presumably, Airship Modern) will be preferred.

Goals:
- Small filesize (under 100 kB for all CSS, images, etc. total)
- Mobile responsive
- Appeals to people whose priorities are for prettiness rather than security

**Comment by rocketpastsix** [comment]
"Appeals to people who care more about pretty/shiny than security/usability"

People want both, but unfortunately when it comes to non-technical businesses, they will pick design over security. 

If you want to avoid paying out for a designer, get bootstrap, and just use simple design patterns to make it happen. It does not need to be fancy or flashy, but it needs to look modern. It needs to look like something people can go to their marketing team and get approval.

**Comment by paragonie-scott** [comment]
> If you want to avoid paying out for a designer, get bootstrap, and just use simple design patterns to make it happen.

I would much rather pay someone who knows what they're doing than frustrate myself for months just to be told it's not good enough.

**Comment by rocketpastsix** [comment]
Then look at Jack McDade I think it is. He does the Laravel series of sites.

**Comment by paragonie-scott** [comment]
Thanks for the recommendation. When the time comes, I'll be sure to reach out to that person.

**Comment by co60ca** [comment]
Looking at https://CSPR.NG I personally think that 90% is cosmetics (as apposed to structural.) And can be improved with colour swaps and maybe reworking the logo.

I'm preparing for classes otherwise I'd give it a shot. Maybe in the future.

**Comment by paragonie-scott** [comment]
We need to actually get a logo made. That filler was the CEO's design and even he's not happy with it.

**Comment by paragonie-scott** [comment]
I'm going to close this because its scope is actually wrong. We need multiple options, out-of-the-box.
