### ISSUE TITLE
Redundant CSS files

### ISSUE THREAD

**Issue by rocketpastsix** [paragonie/airship#123]
- [ ] Check this box if this is a security vulnerability.

### Summary
Looking in src/public/css you have both the bootstrap css and pure css, if you arent using bootstrap, you should remove it. 

### Relevant Debug Information

If you access `$bridge_url/help` as a privileged user, you will be greeted with
a bunch of JSON scripts. At minimum, the "PHP Configuration" box will be useful
for diagnosing any problems. Please paste it below:

```json
. . . PASTE RELEVANT CONFIGURATION JSON IN PLACE OF THIS . . .
```

Alternatively, feel free to delete this section.

**Comment by paragonie-scott** [comment]
Yeah, that's a good idea.

**Comment by rocketpastsix** [comment]
Ive made two PR's to remove the CSS, I didn't get the JS thats in there, but I know its there too.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/ce3e5b11a751a023c32983204a48d2c30b5281ea + https://github.com/paragonie/airship/commit/e805459bac6d593ef0ca3a2788388f0ddd4ec6ea

Thanks for helping out. :+1:
