### ISSUE TITLE
Weak password gives error on login to the bridge

### ISSUE THREAD

**Issue by co60ca** [paragonie/airship#134]
This is on master 4a8a15ab53473ad8591ead53a7e2e3cd9b21152c

- [ ] Check this box if this is a security vulnerability.

### Summary

Steps:
docker-compose up
wait 10s
Database config:
host: database
user: airship
password: secret
database: airship
<enter>

Administrator user: (I retype this if it matters)
captain
Administrator password (lol, it shows an error at this time in red text)
password
<enter> (uses the default config)

Click the bottom to login to the bridge
type captain, <tab> type password <enter>

![screenshot_2016-08-29_21-30-38](https://cloud.githubusercontent.com/assets/6857411/18072941/2e3a755a-6e30-11e6-9eb1-529c2fd62bfc.png)

### Expected Outcome
Either do not allow me to continue with setup, or do allow me to login with a bad password

If you use a "strong" password like the date from the apache logs: 30/Aug/2016:01:30:38 +0000
this error does not occur.

### What Actually Happened
Opposite of above.

If any other errors are being printed elsewhere I do not know where to find them

error.log
```

[Tue Aug 30 01:30:31.976998 2016] [:error] [pid 7] [client 192.168.2.101:51460] PHP Notice:  Undefined index: lang in /var/www/airship/src/Installer/Install.php on line 570, referer: http://appserv-ub03:8080/
[Tue Aug 30 01:30:31.977258 2016] [:error] [pid 7] [client 192.168.2.101:51460] PHP Notice:  Undefined index: lang in /var/www/airship/src/Installer/Install.php on line 570, referer: http://appserv-ub03:8080/
[Tue Aug 30 01:30:35.723135 2016] [:error] [pid 7] [client 192.168.2.101:51460] PHP Notice:  Undefined index: passphrase in /var/www/airship/src/Installer/Install.php on line 830, referer: http://appserv-ub03:8080/

```

**Comment by paragonie-scott** [comment]
I suspect you found a bug in the installer unrelated to password strength.

**Comment by co60ca** [comment]
Occurs with 12345678 as well, but as above '30/Aug/2016:01:30:38 +0000' worked fine

**Comment by paragonie-scott** [comment]
Can you try again with `master` and tell me if this error is still happening?
