### ISSUE TITLE
Default Blog Sub-Header Shown When Null

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#136]
### Summary

The default value for the Hull "Blog Sub-Header" setting will display when the value is set to null.

### Expected Outcome

When the value is cleared, nothing should be displayed.

### What Actually Happened

The phrase "Even the sky shall not limit you." is displayed.

**Comment by paragonie-scott** [comment]
This will be fixed in v1.3.1.

Thanks Adam.

**Comment by adamcaudill** [comment]
👍  Looks good, working as expected now.
