### ISSUE TITLE
Delete Author profiles

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#137]
### Summary

There isn't an (obvious) way to delete Author profiles.

### Expected Outcome

There should be an option to remove an author profile, if it isn't needed (such as the default caption author). I see two ways of doing this:

1. When deleting, if the Author has content associated with it, user is prompted to select an existing Author profile to transfer it to. More complicated to implement, but easier to use.
2. When deleting, if the Author has content associated with it, user is alerted to manually assign all content to another Author before deleting.

### What Actually Happened

No option to delete is provided.

**Comment by paragonie-scott** [comment]
Done in https://github.com/paragonie/airship/pull/154/commits/55215deef18c7e2de3d43da83e0fbdcb9d13d4a5

Will be released with v1.4.0.
