### ISSUE TITLE
Hide "About the Author"

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#139]
### Summary

Some users / authors may not use the "About the Author" section. There should be a way to disable it, when not needed. This is a feature that makes sense on multi-user blogs, but on a single user system, may not add any value.

### Expected Outcome

There should be an option, perhaps as part of the Author profile, to display / not display the "About the Author" section on blog posts.

### What Actually Happened

There is no obvious way to disable that feature.

**Comment by paragonie-scott** [comment]
The immediate problem will be fixed in v1.3.1. By fixed I mean: If you have an empty bio, it will omit the entire section.

In a future version (v1.4.0), a checkbox for the author might be desirable instead.

**Comment by adamcaudill** [comment]
👍  Working as expected - thanks!

**Comment by paragonie-scott** [comment]
Groovy. :)
