### ISSUE TITLE
Only show "Uncategorized" when not empty.

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#142]
### Summary

Currently, the "Uncategorized" category is always displayed, even when there are no posts that are missing a category. If the count of Uncategorized posts is zero, it shouldn't be displayed.

### Expected Outcome

Assigning all posts to a category results in the now empty "Uncategorized" category being removed from the list.

### What Actually Happened

"Uncategorized" is still displayed, and returns no results when clicked.

**Comment by paragonie-scott** [comment]
This will be included in the v1.3.1 bugfix release.

Once again, thank you for finding and reporting these bugs.

**Comment by adamcaudill** [comment]
👍 Working as expected, thanks!
