### ISSUE TITLE
Unable To Edit Posts

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#143]
### Summary

When editing an existing post, an error is received related to the "Date/Time Published" field; the error reads: "Please match the requested format"

### Expected Outcome

Update completes without error.

### What Actually Happened

An error is received, and the field must be cleared to update the post.

**Comment by paragonie-scott** [comment]
This should be fixed soon, but I'm going to test everything again with fresh eyes to be sure.

**Comment by adamcaudill** [comment]
👍  Latest code is working as expected now.
