### ISSUE TITLE
New Blog Post doesn't respect Default Format setting.

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#145]
### Summary

The Bridge "Default Format" setting allows the user to select a default format. This is not used for the New Blog Post page.

### Expected Outcome

When the Default Format is set to Markdown, the New Blog Post page should default to Markdown.

### What Actually Happened

When the Default Format is set to Markdown, the New Blog Post page uses the Rich Text editor.

**Comment by paragonie-scott** [comment]
Hmm, wasn't able to reproduce locally tonight. I might have inadvertently fixed the problem here with my earlier changes. I'll investigate in detail tomorrow.

**Comment by adamcaudill** [comment]
This just became a bit more strange. I change the Default Format to Rich Text, with the intention of changing it back to Markdown - but the change didn't take. Made the change, saved it, forced a reload - and it's back to Markdown.

This is with the latest master - so it's still happening, to me at least.
