### ISSUE TITLE
Purge Cache

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#146]
Ideally, in Bridge -> Cabins -> Hull -> Manage -> Cabin Configuration, there should be a button to perform an immediate purge of the cache. This would be useful when making changes that could invalidate the cache contents (manually clearing the cache is easy enough, though not ideal for typical users).

**Comment by paragonie-scott** [comment]
:+1: There's an AJAX endpoint already; making a button for that should be simple enough.

The URL is: `://{hull}/ajax/clear_cache/{secret goes here}`

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/7b35063b6781bb2c347bb345b2f36d3e9a2a94ca
https://github.com/paragonie/airship/commit/3ba8ea52ce68d67d0dfa15606527e0690d9a48cb
