### ISSUE TITLE
Post History Doesn't Work

### ISSUE THREAD

**Issue by adamcaudill** [paragonie/airship#149]
When clicking on the History link on `/bridge/blog/post`, it redirects to `/bridge/blog/post/history/1` - though that is just a duplicate of the `/bridge/blog/post`. I would assume that this should do something different.

It appears that this functionality is entirely broken.

**Comment by paragonie-scott** [comment]
Even worse than being entirely broken, it turns out that this feature is entirely *missing* from blog posts (sans the currently-useless button) because I implemented it for custom web pages.

Thank you for catching this!

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/de4676c3baf70c07af57ddf094fc293867aca01a
