### ISSUE TITLE
PHP Warning:  symlink(): File exists in /src/Installer/Commands.php on line 41

### ISSUE THREAD

**Issue by snassar** [paragonie/airship#174]
- [ ] Check this box if this is a security vulnerability.

### Summary

`php src/Installer/launch.php reset` shows a PHP warning. It is unclear if this affects the script.

### Expected Outcome

A status message or no message.

### What Actually Happened

Running `php src/Installer/launch.php reset` displays `PHP Warning:  symlink(): File exists in /home/snassar/Websites/airship.dev/src/Installer/Commands.php on line 41`

### Labels Requested

* `ux`
* `papercut`

**Comment by paragonie-scott** [comment]
That's odd. It should be doing an `if this exists and it isn't a symlink, delete it` sort of strategy.
