### ISSUE TITLE
Can't Install on CentOS 7?

### ISSUE THREAD

**Issue by ExoUNX** [paragonie/airship#189]
- [ ] Check this box if this is a security vulnerability.

### Summary

I expect to run the install.sh script but I get the error "Airship requires Libsodium."

### Expected Outcome

For install.sh to run normally

### What Actually Happened

Receives error "Airship requires Libsodium."

### Relevant Debug Information

I grabbed the source from the official libsodium repo, compiled and installed it. I then compiled and installed pecl/libsodium (I wouldn't be able to do that without official libsodium installed.)

here's some text from the php configuration

"
sodium

sodium support => enabled
sodium compiled version => 2.0.4
sodium headers version => 1.0.14
sodium library version => 1.0.14
"

This is on CentOS 7.4
3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

using nginx/1.12.1
and
PHP 7.1.9 (fpm-fcgi) (built: Sep 11 2017 17:01:21)

If you access `$bridge_url/help` as a privileged user, you will be greeted with
a bunch of JSON scripts. At minimum, the "PHP Configuration" box will be useful
for diagnosing any problems. Please paste it below:

```json
. . . PASTE RELEVANT CONFIGURATION JSON IN PLACE OF THIS . . .
```

Alternatively, feel free to delete this section.

### Labels Requested

Feel free to list any labels you feel are appropriate for this issue,
and a member of the Airship core team will apply them as soon as 
possible.

* `label`

**Comment by paragonie-scott** [comment]
Try installing 1.0.6 instead of 2.0.4 of the PECL extension.

**Comment by paragonie-scott** [comment]
Actually, I see the problem. Delete `composer.lock` and then run `composer update`. Halite 3.2 didn't support PECL 2.0.4, but Halite 3.3 does.

**Comment by ExoUNX** [comment]
Alright, downgraded to 1.0.6 and it seems to be resolved. Thank you.
