### ISSUE TITLE
Intent to Abandon Version 1

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship#190]
I'm not going to put a lot of words to this.

Version 1 was a massive failure. Virtually zero adoption in the world, and the PHP community at large has basically given us the middle finger. Web designers are quick to decry it as "ugly", but nobody will lift a finger to improve anything.

Instead of merely releasing version 2 in 2018 and keeping support for both versions, it is my intent to just stop supporting the version 1 branch (effective immediately), and treat it as an extended beta.

With libsodium coming in PHP 7.2, we can see a lot better adoption. That will make Airship more accessible to lay PHP developers. That will make it easier to contain, test, and document. Version 2 has the potential to be something great.

What this means in practice is:

1. There will be no v1.x releases.
2. Until version 2 is released, no more bug reports will be accepted for Airship on HackerOne.

**Comment by cordoval** [comment]
i was using as my leading reference, sorry to hear this, i will still have it as my primary reference.
Some crazy great stuff here, just not understood for folks of this time. 👍

**Comment by paragonie-scott** [comment]
Despite hearing from a dozen people through various channels, nobody has offered a dissenting opinion on this matter, so, consider it done.
