### ISSUE TITLE
Airship 2 doesn't see sodium from PHP 7.2

### ISSUE THREAD

**Issue by alfalfascout** [paragonie/airship#192]
- [ ] Check this box if this is a security vulnerability.

### Summary

I built and installed php 7.2 the day it came out, so I could install from the master branch of Airship. I made certain that extension=sodium was built, installed, and enabled, as well as everything else Airship's composer script required. The composer script itself ran without any problem. But `php src/Installer/launch.php` brings the message: `Airship requires Libsodium.`

### Expected Outcome

I could sail my airship.

### What Actually Happened

It still requires libsodium??

**Comment by paragonie-scott** [comment]
It looks like I forgot to rename it there. If you pull dev-master it should work now.

**Comment by alfalfascout** [comment]
Thanks! I'm not getting that message anymore.
