### ISSUE TITLE
"Outdated Version of Libsodium" notice from public/launch.php on PHP 7.2

### ISSUE THREAD

**Issue by alfalfascout** [paragonie/airship#193]
- [ ] Check this box if this is a security vulnerability.

### Summary

I have PHP 7.2 installed. I have the extension sodium at version 2.0.10. I have libsodium-dev version 1.0.11-2 armhf. I'm running airship on the master branch from 5dddef8. Yet, I can't finish the web installation because public/launch.php informs me my libsodium is outdated.

### Expected Outcome

A web installer would appear when I open public/launch.php

### What Actually Happened

I get a page that starts like this...
```
Error: Outdated Version of Libsodium

CMS Airship's minimum requirements are:

PHP 7.0
libsodium 1.0.9
PECL libsodium 1.0.6

We detected an older version of either libsodium or PECL libsodium.
``` 

### Relevant Debug Information

`$ sudo pecl install libsodium
pecl/libsodium is already installed and is the same as the released version 2.0.10`

`$ apt list libsodium-dev
Listing... Done
libsodium-dev/stable,now 1.0.11-2 armhf [installed]`

`$ php-fpm --version
PHP 7.2.0 (fpm-fcgi) (built: Dec  1 2017 08:19:45)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies`

**Comment by paragonie-scott** [comment]
The error page is outdated, Airship 2 requires 1.0.13+ rather than 1.0.11.

**Comment by alfalfascout** [comment]
I have installed libsodium version 1.0.15 and reinstalled ext-sodium. I also restarted nginx. I'm getting the same page that tells me my libsodium is outdated, though. 

Here's a var_dump test script and its result:
```
<?php
var_dump([
    SODIUM_LIBRARY_MAJOR_VERSION,
    SODIUM_LIBRARY_MINOR_VERSION,
    SODIUM_LIBRARY_VERSION
]);
-----Result:
array(3) {
  [0]=>
  int(10)
  [1]=>
  int(0)
  [2]=>
  string(6) "1.0.15"
}
```

What else could I have missed?

**Comment by alfalfascout** [comment]
Apparently, restarting the nginx server isn't enough. I also had to manually stop and start the php-fpm service before it would start using the new version of the extension. Now that part is working. Thanks for letting me know that I needed a later version of libsodium.

**Comment by paragonie-scott** [comment]
Oh, right. `service nginx restart` needs to be accompanied by `service php-fpm restart`. It's an extra step that LAMP stacks don't require, but FPM setups do.
