### ISSUE TITLE
Document UX Wins

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship#20]
Between now and version 1.0.0, we should make a list of things Airship does better than the existing CMSes, and how these benefits relate to (quoting a [Reddit post with feedback from bopp](https://www.reddit.com/r/PHP/comments/4ie5v9/keyggdrasil_continuum_and_the_cryptography/d2ydccb)):

* Developers: These are the backend-developers. The people who install the CMS, configure it, and build any custom functionality.
* Implementors: These are the "frontend developers". The people who structure the content, set up the contenttypes, and implement the theming of the website in HTML/CSS in the templating language provided by the CMS.
* Editors: These are the people who work in the CMS on a daily basis. They write new content, edit existing pages, etc.

I'd also like to add to this list for a few more use-cases:

* Pseudonymous publishers: Activists or entertainers who wish to publish their content on a Tor Hidden Service for their safety and/or to protect the enigma of their persona. We should go out of our way to protect the server's IP and use authors rather than users for any public interaction.

**Comment by paragonie-scott** [comment]
## User Experience Wins

Tthis comment will be edited frequently.

### All Users

- [ ] Static page caching (cuts response time to less than 1ms on modest hardware)
- [ ] When you delete a blog post or custom page, you can specify a URL to redirect visitors so they don't get the dreaded 404 page
- [ ] Separation of username (for access controls) and author profile (for publishing)

### Editors

- [ ] Multiple text formats
   * Rich text (HTML with a WYSIWYG interface)
   * Raw HTML
   * Markdown
   * ReStructuredText
- [ ] Recursive blog category structure
- [ ] Blog Series
   - [ ] Can be organized however the editor wants
   - [ ] Each blog post can be assigned to any number of series

### Pseudonymous Publishers

- [ ] All outbound HTTP/HTTPS requests can be forcefully proxied over Tor
   * Yes, including ReCAPTCHA

### Developers

- [ ] Ed25519-signed JSON communication
   * I'm not kidding. The API for taking advantage of this is quite simple, too.
- [ ] Best-in-class cryptographic features powered by [Halite](https://paragonie.com/blog/2016/05/solve-all-your-cryptography-problems-in-three-easy-steps-with-halite).
- [ ] (WIP) Barge: a simple command line interface for creating, building, signing, and releasing Airship Cabins and Gadgets.

### Implementors

- [ ] (WIP) Barge: a simple command line interface for creating, building, signing, and releasing Airship Motifs.
- [ ] Uses Twig, which is a more sane templating language than Smarty.

### Security Benefits

- [ ] Secure password storage
- [ ] Automatic updates
   * Also available to extension developers
   * Much more secure than any other self-updating mechanism
   * [Read about its benefits here](https://paragonie.com/blog/2016/05/keyggdrasil-continuum-cryptography-powering-cms-airship)

**Comment by Petah** [comment]
How about multiple blocks? Drag and drop layout management? Navigation editors, image galleries, site maps and full site search?

This is coming from a content editor perspective.

**Comment by paragonie-scott** [comment]
> How about multiple blocks?

Motifs consist of two parts: Static resources (CSS, JS), and Twig templates. You can override the "base template" by changing one line in the motif.json file to completely restructure everything.

Gadgets can override specific templates (e.g. via the [Cargo API](https://github.com/paragonie/airship/blob/master/src/Cabin/Bridge/Lens/cargo/README.md)).

> Drag and drop layout management?

That's an idea worth considering.

> Navigation editors, image galleries, site maps and full site search?

* Navigation editors: You can change what goes in the navbar, but that's something better-suited for a gadget than core functionality.
* Image galleries: That's a good idea.
* Site maps: Intended to be baked in.
* Full site search: Not implementing in version 1, because I need to do more research on search engine development and then design it to not be a denial of service vector.

---
Thanks for the suggestions! :+1:

**Comment by carnage** [comment]
How about 2 factor auth?

**Comment by paragonie-scott** [comment]
How to implement it?

* Google Authenticator - hostile towards Tor users
* SMS - requires a phone number and Twilio account
* Yubikey - requires additional hardware

**Comment by carnage** [comment]
GPG encrypted email?

**Comment by paragonie-scott** [comment]
Already implemented. :)

**Comment by carnage** [comment]
as a 2fa mechanism?

**Comment by paragonie-scott** [comment]
As part of account recovery.

**Comment by paragonie-scott** [comment]
I'll make a ticket for implementing 2FA, but I'm not sure if it will land before v1.0.0 due to the anticipated research burden and short time table.

**Comment by paragonie-scott** [comment]
Okay, this list is good. I'll get around to writing this before v1
