### ISSUE TITLE
Update Readme.md to clarify free software language

### ISSUE THREAD

**Issue by co60ca** [paragonie/airship#26]
### Summary
As on Twitter it may be pertinent to explain that the commercial license is available to companies that require commercial licenses and does not preclude uses in other projects that: are free to use, free to distribute, or free to sell as per the language of the GPL.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/b0b3d72c4ae95dc02b5692fe2df8526c24d35593 Is that an improvement?

**Comment by co60ca** [comment]
I suppose so!
