### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship#30]
Preliminary Requirements:

* Needs to work in a Tor-friendly environment, no metadata or real identity attachments like Google Auth
* Needs to work for people without special hardware
* Needs to be easy-to-use; not GPG-encrypted emails.

The end goal might end up being *multiple* 2FA options, with the Airship captain choosing which ones they want to support.

**Comment by alfiepates** [comment]
I'd suggest you support FIDO U2F. It's not ideal, it _does_ require hardware, but that hardware is pretty damn cheap and readily available.

**Comment by paragonie-scott** [comment]
If "hardware" can also mean "smartphone" then that's acceptable.

**Comment by paragonie-scott** [comment]
FIDO U2F seems like a good idea, but I'm not holding 1.0.0 back on this.

**Comment by kelunik** [comment]
> no metadata or real identity attachments like Google Auth

You mean no TOTP by that?

**Comment by paragonie-scott** [comment]
If we can exchange a shared secret between the server and U2F device without *any* service needing their real name or email address, that requirement is met.

**Comment by kelunik** [comment]
In that case TOTP is perfectly fine and compatible with Google Authenticator.

**Comment by paragonie-scott** [comment]
The good news is: this is getting bumped to version 0.3.0.

The bad news is: Version 0.3.0 is getting bumped down in time by, presumably, a few days.

**Comment by paragonie-scott** [comment]
It looks like Google Authenticator requires Base32 encoding. Luckily, we already have [constant-time RFC 4648 encoding](https://github.com/paragonie/constant_time_encoding) :)

**Comment by kelunik** [comment]
@paragonie-scott Right, and also supports just 6 digits.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/94f03d6dc9f5729d11f0179aee5c0ef345193b38
