### ISSUE TITLE
Invalid CSRF token results in notice

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#41]
https://github.com/paragonie/airship/blob/master/src/Engine/Security/CSRF.php#L123 will raise a notice if there's no `:` (colon) in the provided token. It's rejected, but clean code shouldn't throw any notices.

**Comment by paragonie-scott** [comment]
Absolutely. Thanks for looking through the code. This commit should fix any `list()`-based notices: https://github.com/paragonie/airship/commit/3b620cce174020b38c3ff93a536b8acaa512b0af

**Comment by kelunik** [comment]
Can we close this then?
