### ISSUE TITLE
Dockerfile for easy deployment

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#42]
There should be a `Dockerfile` to make deployment easy. This especially makes it easier to set it up to  have just a quick look at it.

**Comment by paragonie-scott** [comment]
Indeed. Easy deployment is a huge priority for us. :+1:

**Comment by paragonie-scott** [comment]
This actually looks rather straightforward.

[This guide uses `apt-get`](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/); is that generally available in Docker? Or should we detect which package manager and write scripts for `yum`, `zyp`, `pacman`, etc. as well?

**Comment by kelunik** [comment]
Yes, you base your images on base images, so you can just base it on `FROM ubuntu:16.04`.

**Comment by kelunik** [comment]
I currently end up with https://gist.github.com/kelunik/ff63fff2c208aca8c5a1883344a9789b using https://gist.github.com/kelunik/ccc412ac0ed9c9899e92ab04461394f0

**Comment by co60ca** [comment]
I remember having issues with PECL but alas my .bash_history got erased

**Comment by paragonie-scott** [comment]
I've been talking with @kelunik over Twitter. The PECL issues were fixed, but the Postgres setup isn't working yet.

**Comment by co60ca** [comment]
See #55 for reasons why Postgres wasn't working

**Comment by co60ca** [comment]
We should close this issue with #58 and consider opening another issue for better management of the container, I'm not 100% but I believe that most people create separate storage for logs, exposing ports using the EXPOSE tag in the Dockerfile ect...

**Comment by paragonie-scott** [comment]
Awesome work, @co60ca! :+1:
