### ISSUE TITLE
Sodium Error in Set Up Your Administrator Account step

### ISSUE THREAD

**Issue by co60ca** [paragonie/airship#56]
- [ ] Check this box if this is a security vulnerability.

### Summary
From the docker image in #55 if you use:
```
host: localhost
user: airship
password: secret
database: airship
```
for the Database setup screen then use seemingly any username/password combination for the step in question you will get a 500 error and the following message in error.log in apache.

```
[Thu Jun 30 22:00:53.693308 2016] [:error] [pid 20] [client 192.168.2.146:35356] PHP Fatal error:  Uncaught Error: Undefined constant 'Sodium\\CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE' in /var/www/airship/vendor/paragonie/halite/src/KeyFactory.php:344\nStack trace:\n#0 /var/www/airship/vendor/paragonie/halite/src/Password.php(30): ParagonIE\\Halite\\KeyFactory::getSecurityLevels('interactive')\n#1 /var/www/airship/src/Installer/Install.php(235): ParagonIE\\Halite\\Password::hash('areallyfuckingl...', Object(ParagonIE\\Halite\\Symmetric\\EncryptionKey))\n#2 /var/www/airship/src/Installer/Install.php(115): Airship\\Installer\\Install->processAdminAccount(Array)\n#3 /var/www/airship/src/Installer/launch.php(171): Airship\\Installer\\Install->currentStep()\n#4 /var/www/airship/src/public/index.php(26): include('/var/www/airshi...')\n#5 {main}\n  thrown in /var/www/airship/vendor/paragonie/halite/src/KeyFactory.php on line 344, referer: http://appserv-ub03:8080/
```
### Expected Outcome
Move onto the next setup screen

### What Actually Happened
500 server error.

Also it appears the password is leaked here again 'areallyfuckingl...'

**Comment by paragonie-scott** [comment]
Yeah, the `HiddenString` thing isn't part of `Halite`. I'll probably add that in version 3.

Anyway, run this:

```php
<?php
use \ParagonIE\Halite\Halite;

// TRUE enables verbose output:
Halite::isLibsodiumSetupCorrectly(true);
```

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/414c3b598404135687b390fe2768f4733c88a5d7 will kill the installer if you're using libsodium v1.0.8, which is what I believe `libsodium-dev` provides currently.

There's a reason the documentation explicitly compiles from source. :(

**Comment by co60ca** [comment]
I'll give the setup a shot again with the previous instructions. I saw the error, and we should consider having a special "error" page like all the CMS's have.

**Comment by paragonie-scott** [comment]
Good idea! This will probably become a frequent problem until Debian/Ubuntu get their act together with security libraries.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/e41b959604c009bc4b55a8e64ea043f9eb8b1736

**Comment by paragonie-scott** [comment]
I believe this is okay to close. If I'm mistaken, feel free to correct me and I'll reopen it.
