### ISSUE TITLE
Generate new signing keys

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship#6]
The original signing keys were generated before Argon2i support was merged. I should generate a new keypair and update the corresponding public keys.

**Comment by paragonie-scott** [comment]
Why this hasn't been done yet:

1. I need to take the time to carefully update libsodium for the airgapped machine.
2. I need to memorize two new high security passwords to the point that I can reliably recall them from memory after a week of not using them.
3. I need to generate two new salts (easy).

**Comment by kmark** [comment]
This may be off topic for this issue but what is the procedure in the event you forgot a password? Would it make sense to have well defined procedures in the unfortunate event there's some kind of breakdown in protocol or other form of trust chain compromise?

**Comment by paragonie-scott** [comment]
That's why we have two passwords/keys.

The backup is only known by me and the CEO (in case, e.g. I have head
trauma), but the day to day one is only known by me. The backup one should
only be used to sign new regular-use keys. If this is ever violated, assume
NSL or worse.

**Comment by kmark** [comment]
Great, thanks for the clarification.

**Comment by paragonie-scott** [comment]
This has been done, I just need to copy the public keys over.

**Comment by paragonie-scott** [comment]
Redoing this with Halite 2.1.0 so I can use `SENSITIVE` for the key derivation. Expect a public key update tonight.
