### ISSUE TITLE
Why is session index an option

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#63]
Why is the session index for the `userid` even an option? Why would I ever change this?

**Comment by paragonie-scott** [comment]
The use-case I had in mind when I wrote that part in May 2015 was, "What if they have several applications with the same PHPSESSID cookie and use the same generic backend session index?" to prevent lateral privilege escalation... but really we should just standardize on, e.g. `"airship_userid"` and not make this an option.

**Comment by kelunik** [comment]
Should be enough to use `userid` and a custom session cookie name?

**Comment by paragonie-scott** [comment]
Yeah, that works too. :)
