### ISSUE TITLE
Guest group doesn't have default

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#64]
The guest group doesn't have `Guest` selected by default. Dunno whether it's a display or configuration failure.

![image](https://cloud.githubusercontent.com/assets/2743004/16515778/44957718-3f74-11e6-82e1-e459b9e9c72c.png)

**Comment by paragonie-scott** [comment]
Thanks, this should take care of that: https://github.com/paragonie/airship/commit/b80e8403d7e8949f0aca26eca259acf84f1edfcf
