### ISSUE TITLE
Datebase settings is an empty page

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#65]
### Summary

http://localhost:8001/bridge/admin/database

### Expected Outcome

A non-empty page.

### What Actually Happened

An empty page.

![image](https://cloud.githubusercontent.com/assets/2743004/16515831/96dc217a-3f74-11e6-96e0-7f969c61c8f6.png)

**Comment by paragonie-scott** [comment]
Hmm, yeah, I knew I forgot something. This was meant to just be a page for managing database credentials. Given #57 this is probably somewhat of a mixed blessing.

**Comment by co60ca** [comment]
I saw this too but forgot D:

Have we considered using an interactive testing framework? The one laravel used for page navigation was handy, not sure if one exists for generic websites.
