### ISSUE TITLE
Why is google.com CSP-whitelisted by default?

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#68]
https://www.google.com and https://www.gstatic.com are whitelisted by default, they probably shouldn't.

**Comment by paragonie-scott** [comment]
Google Web Fonts + ReCAPTCHA.

**Comment by kelunik** [comment]
Needs an explanation then or should be hardcoded if captchas are enabled.

**Comment by kelunik** [comment]
I think this one need `ux` as well.
