### ISSUE TITLE
Easier setup

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#70]
Setup should be easier. Currently there are 4 or more pages. Most settings don't have to be changed. They should just have reasonable defaults. Most of them are changeable at any time later.

Especially advanced options shouldn't show up. If you want to show them, ask beforehand if you want to continue configuring or just start.

**Comment by paragonie-scott** [comment]
Okay, after setting up the database and admin account, I'll create a "Easy Install" button that skips the rest of the configuration steps.
