### ISSUE TITLE
Double saving of forms

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#73]
### Summary

Double saving of forms isn't handled gracefully. If I hit F5 after saving some settings, the CSRF token is already expired.

### Expected Outcome

Should be handled gracefully or better not even happen. A possible solution is to use the [Post / Redirect / Get](https://en.wikipedia.org/wiki/Post/Redirect/Get) pattern.

### What Actually Happened

```
DEBUG ERROR: Airship\Alerts\Security\SecurityAlert

CSRF validation failed

0

#0 /var/www/airship/src/Cabin/Bridge/Landing/Admin.php(183): Airship\Engine\Landing->post(Object(Airship\Cabin\Bridge\Filter\Admin\SettingsFilter))
#1 /var/www/airship/src/Engine/AutoPilot.php(429): Airship\Cabin\Bridge\Landing\Admin->manageSettings()
#2 /var/www/airship/src/Engine/AutoPilot.php(264): Airship\Engine\AutoPilot->serve(Array, Array)
#3 /var/www/airship/src/public/index.php(152): Airship\Engine\AutoPilot->route()
#4 {main}<!-- Load time: 0.45981 s -->
```

Without debug mode, a white page probably.

**Comment by paragonie-scott** [comment]
Without debug mode, CSRF violations return `false` instead of throwing an exception.  But this raises a good point: we should always redirect.

**Comment by co60ca** [comment]
This is why when we had those issues early on and I suggested a custom error page that is all pretty is for stuff like this. User error could be "User session invalid"

**Comment by paragonie-scott** [comment]
That won't be hard to implement. In `public/index.php`:

```php
try {
    $autoPilot->route();
} catch (SecurityAlert $ex) {
    // Pretty page goes here
}
```

**Comment by co60ca** [comment]
Ensure however that we don't leak any private information in the Security Alert Exception if the Pretty page is to print error details that are user friendly.

Conversely you could just throw a static error with every Exception.

**Comment by paragonie-scott** [comment]
We could also do like YouTube and encrypt the stack trace.

**Comment by co60ca** [comment]
If you decide to do that ensure it is configurable :P

**Comment by kelunik** [comment]
Even an error page isn't really user friendly here. Prefilling the form + warning, that the form has to be submitted again could work. On the other hand, that could be used by attackes to prefill values where the user doesn't review all values.

**Comment by paragonie-scott** [comment]
OK, well, I'm definitely going the post-redirect-get route here.

To reiterate: the `SecurityAlert` is only thrown by the CSRF code in debug mode, because it's louder than silently returning `false`. Debug mode is not meant for production environments.

**Comment by paragonie-scott** [comment]
The Admins page was fixed in https://github.com/paragonie/airship/commit/6aff0bc6b165ddbd0b68371cd92ec78fd5567751 -- I'll go through before the next minor release and verify there aren't any I've forgotten.
