### ISSUE TITLE
Poor UX for comment view in Bridge

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#76]
It's not clear on http://localhost:8001/bridge/blog/comments that the search icon is a link / the only link that can be used to approve the comments.

I propose to have the comment's contents directly in the list with approve and deny buttons, something like https://dribbble.com/shots/214434-Comment-Approval-System

**Current State**

![image](https://cloud.githubusercontent.com/assets/2743004/16532734/2c6c5ea8-3fd4-11e6-9d93-5b0e6c4cba99.png)

**Comment by kelunik** [comment]
Prototype: https://jsfiddle.net/d4tub30b/

**Comment by kelunik** [comment]
A more advanced solution could also show results of a automatic spam check as help. Inspiration: https://dribbble.com/shots/8750-Comment-Moderation

**Comment by paragonie-scott** [comment]
Adding an automatic spam check would be useful. How much data do services like Akismet leak? And can they be accessed via Tor? :)

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/40932c3bafedc4a582cc0624bbde55ffdd9162ee should resolve the most annoying UX problems. I'm going to bump this until a later milestone to figure out how to identify anti-spam solutions.
