### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#77]
The last line of the README file says it is fully responsive. Doesn't look like that for me using the Chromium developer tools.

![image](https://cloud.githubusercontent.com/assets/2743004/16533473/350e97ba-3fd9-11e6-8d22-523c138cec39.png)

The header / menu and button fonts are too small.

**Comment by paragonie-scott** [comment]
Chrome seems to ignore `@media` queries :|

**Comment by paragonie-scott** [comment]
I think I fixed most of the issues here. Please let me know if I missed anything egregious.

**Comment by DanielRuf** [comment]
@paragonie-scott I stumbled upon issues like this and thought that there is a `viewport` metatag (needed that it is responsive and font-sizes are properly adjusted) but found none.
