### ISSUE TITLE
Registration shown again after registration

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#78]
After registration on cspr.ng, there shows up the registration page again.

![image](https://cloud.githubusercontent.com/assets/2743004/16541558/5a3990dc-4086-11e6-9780-104a5b3e7d89.png)

This is unexpected.

**Comment by paragonie-scott** [comment]
Did you see the message at the top?

**Comment by kelunik** [comment]
No. And during registration it said it was pretty good.

**Comment by paragonie-scott** [comment]
"Pretty good"? Let me check that I didn't mess with the required Zxcvbn password strength, server-side.

**Comment by kelunik** [comment]
Don't know the term exactly, but it was green.

**Comment by paragonie-scott** [comment]
Does fixing the other zxcvbn bug resolve this too?

**Comment by paragonie-scott** [comment]
This hasn't been reported again, and I haven't encountered it in months, so I'm assuming the fix worked. :)
