### ISSUE TITLE
Password Reset Broken

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#79]
### Summary

Password reset returns an error 500 after submission.

Steps to reproduce:
- Visit https://bridge.cspr.ng/forgot-password
- Type `kelunik` into the username field
- Submit the form

### Expected Outcome

A success / error / some message.

### What Actually Happened

HTTP Error 500, blank page.

**Comment by paragonie-scott** [comment]
I broke a few things. It will be fixed in the next release (1.1.4) in a few minutes.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/f120f13a8bb322d0530b65fe1d227aec1cb9f139 + https://github.com/paragonie/airship/commit/12e9eab19fea307cedfed3498a530cb45f7624f9
