### ISSUE TITLE
Installer CSS not loading

### ISSUE THREAD

**Issue by kmark** [paragonie/airship#8]
### Summary
Installer loads without CSS from the /static/Hull public directory.

### Expected Outcome
Installer loads with styles.

### What Actually Happened
These two guys 404 so we are left with a largely unstyled installer.
```html
<link rel='stylesheet' href='/static/Hull/base.css' />
<link rel='stylesheet' href='/static/Hull/motif/airship-classic/style.css' />
```

My /src/public/static directory is empty.

**Comment by paragonie-scott** [comment]
Interesting. `public/static/Hull` *should* be a symlink to `Cabin/Hull/public`.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/5327abdc760787c8a1a4a7329ab484537a8867f8 should fix this. I'll check in a minute.

**Comment by paragonie-scott** [comment]
Nope, but https://github.com/paragonie/airship/commit/d2436f3d1323394752e46ca19b6c1b8d7062b54b does it.

Thanks again @kmark :)

**Comment by kmark** [comment]
Confirmed, thanks for the fix
