### ISSUE TITLE
Warning when saving account settings

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#82]
I tried to add a display name in `My Account`. The account is the root account created with user `test` and password `test`.

**Result**

The following warning appears: `Warning: log() expects parameter 1 to be float, string given in /var/www/airship/vendor/bjeavons/zxcvbn-php/src/ZxcvbnPhp/Matchers/Match.php on line 201`

**Comment by paragonie-scott** [comment]
I think this is a problem with [zxcvbn-php](https://github.com/bjeavons/zxcvbn-php).

To diagnose better, could you add `declare(strict_types=1)` to `vendor/bjeavons/zxcvbn-php/src/ZxcvbnPhp/Matchers/Match.php`, and then change `log($number)` to `log(float $number)`? That should give a stack trace.

**Comment by kelunik** [comment]
```
DEBUG ERROR: TypeError

Argument 1 passed to ZxcvbnPhp\Matchers\Match::log() must be of the type float, string given, called in /var/www/airship/vendor/bjeavons/zxcvbn-php/src/ZxcvbnPhp/Matchers/DictionaryMatch.php on line 72

0

#0 /var/www/airship/vendor/bjeavons/zxcvbn-php/src/ZxcvbnPhp/Matchers/DictionaryMatch.php(72): ZxcvbnPhp\Matchers\Match->log('username')
#1 /var/www/airship/vendor/bjeavons/zxcvbn-php/src/ZxcvbnPhp/Searcher.php(47): ZxcvbnPhp\Matchers\DictionaryMatch->getEntropy()
#2 /var/www/airship/vendor/bjeavons/zxcvbn-php/src/ZxcvbnPhp/Zxcvbn.php(56): ZxcvbnPhp\Searcher->getMinimumEntropy('testtesttest', Array)
#3 /var/www/airship/src/Cabin/Bridge/Blueprint/UserAccounts.php(644): ZxcvbnPhp\Zxcvbn->passwordStrength('testtesttest', Array)
#4 /var/www/airship/src/Cabin/Bridge/Landing/Account.php(399): Airship\Cabin\Bridge\Blueprint\UserAccounts->isPasswordWeak(Array)
#5 /var/www/airship/src/Cabin/Bridge/Landing/Account.php(176): Airship\Cabin\Bridge\Landing\Account->processAccountUpdate(Array, Array, '')
#6 /var/www/airship/src/Engine/AutoPilot.php(429): Airship\Cabin\Bridge\Landing\Account->my()
#7 /var/www/airship/src/Engine/AutoPilot.php(264): Airship\Engine\AutoPilot->serve(Array, Array)
#8 /var/www/airship/src/public/index.php(152): Airship\Engine\AutoPilot->route()
#9 {main}<!-- Load time: 0.39099 s -->
```

**Comment by paragonie-scott** [comment]
OK, this is likely a problem with how data is being fed into it.

**Comment by kelunik** [comment]
Yes, that array should be an array or values, not associative (int / float keys).

https://github.com/paragonie/airship/blob/master/src/Cabin/Bridge/Blueprint/UserAccounts.php#L641

You should probably not feed in the post data, but instead the user data, so email / name / display name.

**Comment by paragonie-scott** [comment]
I think https://github.com/paragonie/airship/commit/6ce8f2867c10a3f5cb70caf83b96394729815579 will fix this, I'll play around with it a bit more tonight.
