### ISSUE TITLE
Bridge Directory Move Broken

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#85]
### Summary

Moving a directory isn't possible currently.

**Steps to reproduce**

- Go to the Bridge
- Go to Cabins → Bridge → Files (http://localhost:8080/bridge/file_manager/Bridge)
- Create a new directory
- Try to move it by clicking on the move button

### Expected Outcome

A move form.

### What Actually Happened

Redirect to http://localhost:8080/bridge

**Comment by kelunik** [comment]
Same applies to `Delete` for files. `File info` does just nothing.

**Comment by paragonie-scott** [comment]
I'm having trouble reproducing this. I'll look at the code and see if there's anything obvious that could be causing this to break.

**Comment by paragonie-scott** [comment]
Hmm, this could be a problem with Apache not handling the GET parameters correctly.

**Comment by kelunik** [comment]
Fixed via #121.
