### ISSUE TITLE
Bridge Canon URL not respected

### ISSUE THREAD

**Issue by kmark** [paragonie/airship#9]
### Summary
Links to and within the bridge are invalid because the canon URL is not being used or set properly. Reproduced by creating a new airship instance, running the installer and setting a bridge canon URL of whatever.com/bridge

### Expected Outcome
Everything links together. The link to the bridge on the bottom of the Hull should go to /bridge/ on my install.

### What Actually Happened
The Bridge link at the bottom of the Hull just goes to "/". Links within the Bridge (by manually going to /bridge) are invalid as they are missing the bridge prefix. When I go to airship.app/bridge/cabins/manage/Bridge to see what my canon URL is actually set to it was set to "//" despite what I entered in the installer.

Upon correcting that form to the URL I actually want nothing happens to the links. It gives me an additional (unrelated?) PHP error:

```
Warning: file_put_contents(/var/www/src/config/Bridge/content_security_policy.json): failed to open stream: No such file or directory in /var/www/src/Cabin/Bridge/Landing/Cabins.php on line 185
```

**Comment by paragonie-scott** [comment]
Confirmed installer bug. Will fix when I get back to a safe computer.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/99a83b648e70d501bfb3b5dd51ef696c32daf559#diff-fa673210a48ffabb0d668d11fead04b2R319

That should fix it. Sorry about that.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/90bedba71011c4c35b6dda8036f298018d92e93e

**Comment by kmark** [comment]
Confirmed fixed, thanks
