### ISSUE TITLE
Repeated setup doesn't detect already existing database

### ISSUE THREAD

**Issue by kelunik** [paragonie/airship#95]
When using `docker-compose up --force-recreate`, we start in the setup process again. However, the database still exists. Airship should check if the existing schema is fine and use it.

I think we also need a way to completely reset the `pgsql` / `database` container, as recreate doesn't delete the existing data. This is due to volumes being persistent.

`string(83) "SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "airship_users" already exists" string(861) "CREATE TABLE airship_users ( userid BIGSERIAL PRIMARY KEY, username TEXT, password TEXT, totp_secret TEXT, enable_2factor BOOLEAN DEFAULT FALSE, session_canary TEXT, display_name TEXT, email TEXT, uniqueid TEXT, real_name TEXT DEFAULT NULL, birthdate TIMESTAMP NULL, allow_reset BOOLEAN DEFAULT FALSE, gpg_public_key TEXT, custom_fields JSONB NULL, publicprofile BOOLEAN DEFAULT FALSE, superuser BOOLEAN DEFAULT FALSE, created TIMESTAMP DEFAULT NOW(), modified TIMESTAMP DEFAULT NOW() ); CREATE UNIQUE INDEX ON airship_users (username); CREATE UNIQUE INDEX ON airship_users (uniqueid); DROP TRIGGER IF EXISTS update_airship_users_modtime ON airship_users; CREATE TRIGGER update_airship_users_modtime BEFORE UPDATE ON airship_users FOR EACH ROW EXECUTE PROCEDURE update_modtime(); "`

**Comment by paragonie-scott** [comment]
The setup was never intended to be run more than once. You can actually bypass the setup by creating `src/config/databases.json` and a barebones `src/config/cabins.json`.

**Comment by co60ca** [comment]
Is it possible to change to CREATE TABLE IF NOT EXISTS? I tend to use this in my projects

**Comment by paragonie-scott** [comment]
That solves half the problem. Ideally, it should detect "this is already installed" and abort the installer.

**Comment by kelunik** [comment]
`docker-compose rm -v` can be used to delete older container versions including the volumes to remove old databases.

**Comment by paragonie-scott** [comment]
This was done in https://github.com/paragonie/airship/commit/ae047e9806849d4d141046f77fa4253540722b5c.

If the database is already setup, everything gets skipped.
